### ISSUE TITLE
Status Bar

### ISSUE THREAD

**Issue by picard102** [jcitysinner/eggman#1]
- Status is not reflecting the proper state. "Closed" Is showing a "Soon" Class. 
- Map and Sun icons do not show up in "Opened" or "Soon" states.
- Schedule link should smooth scroll to schedule section.
- If no future scheduled dates should still display "Closed" status. 
- State text doesn't match comps.
- Map icon should link to google maps of location.

![screen shot 2015-09-21 at 3 54 00 pm](https://cloud.githubusercontent.com/assets/153334/10003144/03c35cda-6079-11e5-8be9-4c6b8b468904.png)

Comp State Text

![screen shot 2015-09-21 at 4 01 33 pm](https://cloud.githubusercontent.com/assets/153334/10003395/27dff91a-607a-11e5-9b79-853b50ded22e.png)
![screen shot 2015-09-21 at 4 01 58 pm](https://cloud.githubusercontent.com/assets/153334/10003396/27e0bdaa-607a-11e5-958e-a5e4028ecb1f.png)
![screen shot 2015-09-21 at 4 01 40 pm](https://cloud.githubusercontent.com/assets/153334/10003397/27e10134-607a-11e5-8a83-0112367c20bb.png)

**Comment by jcitysinner** [comment]
Complete:
Status is not reflecting the proper state. "Closed" Is showing a "Soon" Class.
Schedule link should smooth scroll to schedule section.
If no future scheduled dates should still display "Closed" status.
State text doesn't match comps.

Not Complete:
Map icon should link to google maps of location.
Map and Sun icons do not show up in "Opened" or "Soon" states.
