### ISSUE TITLE
Social

### ISSUE THREAD

**Issue by picard102** [jcitysinner/eggman#4]
Not something I've implemented before. Tony usually handled it, might be easiest to take a look at the projects he's done it on and use that as an example. I know on LaVie I implemented a instagram feed, but don't have the source files to reference.

**Comment by jcitysinner** [comment]
pulling in 5 most recent instagram posts now

**Comment by picard102** [comment]
Twiiter?

**Comment by jcitysinner** [comment]
Do we need Twitter?

**Comment by picard102** [comment]
They get a fair bit of interaction there.

**Comment by picard102** [comment]
Be good to have instagram pull in the hashtag, as well as images liked by tom's account. Doing the same for twitter. Might have to pull separately and then merge them into an array by date,
